# icon
title_ico = '../pic/line.ico'

# values
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find edges', 'Contour', 'Edge enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False

# Colors
BACKGROUND_COLOR = '#242424'
WHITE = '#FFF'
GREY = 'grey'
BLUE = '#aec2d1'
BLUE_HOVER = '#d3e1eb'
BLUE_BG = '#90a399'
DARK_GRAY = '#4a4a4a'
CLOSE_RED = '#8a0606'
SLIDER_BG = '#64686b'
SLIDER_BUTTON = '#807e7e'
MENU_BG = '#3e3e40'
BUTTON_BG = '#424242'
BUTTON_BG_HOVER = '#5c5c5c'
BUTTON_COLOR = '#4a4a57'
BUTTON_HOVER_COLOR = '#69697d'
DROPDOWN_MAIN_COLOR = '#444'
DROPDOWN_HOVER_COLOR = '#333'
DROPDOWN_MENU_COLOR = '#666'
